Console.Clear();
//Console.SetCursorPosition(40, 10);
//Console.WriteLine("+");
int xa = 1; 
int ya = 1; 
int xb = 1; 
int yb = 20;
int xc = 20;
int yc = 20;
Console.SetCursorPosition(xa, ya);
Console.WriteLine("+");
//Console.SetCursorPosition(xb, yb);
//Console.WriteLine("+");
Console.SetCursorPosition(xc, yc);
Console.WriteLine("+");